In [150]:
import pandas as pd
fact_book= pd.read_csv(r'C:\projects_monish\Hotel Analytics\Hotel-analytics\data\raw\fact_bookings.csv')
fact_abook= pd.read_csv(r'C:\projects_monish\Hotel Analytics\Hotel-analytics\data\raw\fact_aggregated_bookings.csv')
dim_date= pd.read_csv(r'C:\projects_monish\Hotel Analytics\Hotel-analytics\data\raw\dim_date.csv')
dim_hotels= pd.read_csv(r'C:\projects_monish\Hotel Analytics\Hotel-analytics\data\raw\dim_hotels.csv')
dim_rooms= pd.read_csv(r'C:\projects_monish\Hotel Analytics\Hotel-analytics\data\raw\dim_rooms.csv')
print(fact_book.head(4))
print(fact_abook.head(4))

         booking_id  property_id booking_date check_in_date checkout_date  \
0  May012216558RT11        16558   27-04-2022    01-05-2022    02-05-2022
1  May012216558RT12        16558   30-04-2022    01-05-2022    02-05-2022
2  May012216558RT13        16558   28-04-2022    01-05-2022    04-05-2022
3  May012216558RT14        16558   28-04-2022    01-05-2022    02-05-2022

   no_guests room_category booking_platform  ratings_given booking_status  \
0       -3.0           RT1    direct online            1.0    Checked Out
1        2.0           RT1           others            NaN      Cancelled
2        2.0           RT1          logtrip            5.0    Checked Out
3       -2.0           RT1           others            NaN      Cancelled

   revenue_generated  revenue_realized
0              10010             10010
1               9100              3640
2            9100000              9100
3               9100              3640
   property_id check_in_date room_category  successful_bookings  capacity
0        16559    01-05-2022           RT1                   25      30.0
1        19562    01-05-2022           RT1                   28      30.0
2        19563    01-05-2022           RT1                   23      30.0
3        17558    01-05-2022           RT1                   30      19.0

In [151]:
print(dim_date.head(4))
print(dim_hotels.head(4))
print(dim_rooms.head(4))

         date  mmm yy week no  day_type
0  01-05-2022  May-22    W 19   weekend
1  02-05-2022  May-22    W 19  weekeday
2  03-05-2022  May-22    W 19  weekeday
3  04-05-2022  May-22    W 19  weekeday
   property_id  property_name  category    city
0        16558   Atliq Grands    Luxury   Delhi
1        16559  Atliq Exotica    Luxury  Mumbai
2        16560     Atliq City  Business   Delhi
3        16561      Atliq Blu    Luxury   Delhi
  room_id    room_class
0     RT1      Standard
1     RT2         Elite
2     RT3       Premium
3     RT4  Presidential

In [152]:
fact_book.info()

<class 'pandas.DataFrame'>
RangeIndex: 134590 entries, 0 to 134589
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   booking_id         134590 non-null  str
 1   property_id        134590 non-null  int64
 2   booking_date       134590 non-null  str
 3   check_in_date      134590 non-null  str
 4   checkout_date      134590 non-null  str
 5   no_guests          134587 non-null  float64
 6   room_category      134590 non-null  str
 7   booking_platform   134590 non-null  str
 8   ratings_given      56683 non-null   float64
 9   booking_status     134590 non-null  str
 10  revenue_generated  134590 non-null  int64
 11  revenue_realized   134590 non-null  int64
dtypes: float64(2), int64(3), str(7)
memory usage: 12.3 MB

In [153]:
# Convert date columns to datetime type for analysis
fact_book['booking_date'] = pd.to_datetime(fact_book['booking_date'], dayfirst=True)
fact_book['check_in_date'] = pd.to_datetime(fact_book['check_in_date'], dayfirst=True)
fact_book['checkout_date'] = pd.to_datetime(fact_book['checkout_date'], dayfirst=True)

fact_abook['check_in_date'] = pd.to_datetime(fact_abook['check_in_date'], dayfirst=True)

print("Date columns converted to datetime type")
print(f"fact_book dtypes:\n{fact_book[['booking_date', 'check_in_date', 'checkout_date']].dtypes}")
print(f"\nfact_abook check_in_date dtype: {fact_abook['check_in_date'].dtype}")

Date columns converted to datetime type
fact_book dtypes:
booking_date     datetime64[us]
check_in_date    datetime64[us]
checkout_date    datetime64[us]
dtype: object

fact_abook check_in_date dtype: datetime64[us]

In [154]:
fact_book.describe()

,property_id,booking_date,check_in_date,checkout_date,no_guests,ratings_given,revenue_generated,revenue_realized
count,134590.000000,134590,134590,134590,134587.000000,56683.000000,1.345900e+05,134590.000000
mean,18061.113493,2022-06-11 05:51:49.871462,2022-06-14 22:52:29.939817,2022-06-17 07:51:51.262352,2.036170,3.619004,1.537805e+04,12696.123256
min,16558.000000,2022-04-07 00:00:00,2022-05-01 00:00:00,2022-05-02 00:00:00,-17.000000,1.000000,6.500000e+03,2600.000000
25%,17558.000000,2022-05-19 00:00:00,2022-05-23 00:00:00,2022-05-25 00:00:00,1.000000,3.000000,9.900000e+03,7600.000000
50%,17564.000000,2022-06-11 00:00:00,2022-06-15 00:00:00,2022-06-17 00:00:00,2.000000,4.000000,1.350000e+04,11700.000000
75%,18563.000000,2022-07-04 00:00:00,2022-07-08 00:00:00,2022-07-10 00:00:00,2.000000,5.000000,1.800000e+04,15300.000000
max,19563.000000,2022-07-31 00:00:00,2022-07-31 00:00:00,2022-08-06 00:00:00,6.000000,5.000000,2.856000e+07,45220.000000
std,1093.055847,NaN,NaN,NaN,1.034885,1.235009,9.303604e+04,6928.108124

In [155]:
#negative values
fact_book[fact_book['no_guests'] <= 0]

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT11,16558,2022-04-27,2022-05-01,2022-05-02,-3.0,RT1,direct online,1.0,Checked Out,10010,10010
3,May012216558RT14,16558,2022-04-28,2022-05-01,2022-05-02,-2.0,RT1,others,NaN,Cancelled,9100,3640
17924,May122218559RT44,18559,2022-05-12,2022-05-12,2022-05-14,-10.0,RT4,direct online,NaN,No Show,20900,20900
18020,May122218561RT22,18561,2022-05-08,2022-05-12,2022-05-14,-12.0,RT2,makeyourtrip,NaN,Cancelled,9000,3600
18119,May122218562RT311,18562,2022-05-05,2022-05-12,2022-05-17,-6.0,RT3,direct offline,5.0,Checked Out,16800,16800
18121,May122218562RT313,18562,2022-05-10,2022-05-12,2022-05-17,-4.0,RT3,direct online,NaN,Cancelled,14400,5760
56715,Jun082218562RT12,18562,2022-06-05,2022-06-08,2022-06-13,-17.0,RT1,others,NaN,Checked Out,6500,6500
119765,Jul202219560RT220,19560,2022-07-19,2022-07-20,2022-07-22,-1.0,RT2,others,NaN,Checked Out,13500,13500
134586,Jul312217564RT47,17564,2022-07-30,2022-07-31,2022-08-01,-4.0,RT4,logtrip,2.0,Checked Out,38760,38760

In [156]:
# non negative values
fact_book=fact_book[fact_book['no_guests'] >0]
fact_book

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
1,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2.0,RT1,others,NaN,Cancelled,9100,3640
2,May012216558RT13,16558,2022-04-28,2022-05-01,2022-05-04,2.0,RT1,logtrip,5.0,Checked Out,9100000,9100
4,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4.0,RT1,direct online,5.0,Checked Out,10920,10920
5,May012216558RT16,16558,2022-05-01,2022-05-01,2022-05-03,2.0,RT1,others,4.0,Checked Out,9100,9100
6,May012216558RT17,16558,2022-04-28,2022-05-01,2022-05-06,2.0,RT1,others,NaN,Cancelled,9100,3640
...,...,...,...,...,...,...,...,...,...,...,...,...
134584,Jul312217564RT45,17564,2022-07-30,2022-07-31,2022-08-01,2.0,RT4,others,2.0,Checked Out,32300,32300
134585,Jul312217564RT46,17564,2022-07-29,2022-07-31,2022-08-03,1.0,RT4,makeyourtrip,2.0,Checked Out,32300,32300
134587,Jul312217564RT48,17564,2022-07-30,2022-07-31,2022-08-02,1.0,RT4,tripster,NaN,Cancelled,32300,12920
134588,Jul312217564RT49,17564,2022-07-29,2022-07-31,2022-08-01,2.0,RT4,logtrip,2.0,Checked Out,32300,32300
134589,Jul312217564RT410,17564,2022-07-31,2022-07-31,2022-08-01,2.0,RT4,makeyourtrip,NaN,Cancelled,32300,12920

In [157]:
fact_book.revenue_generated.min(),fact_book.revenue_generated.max()

(np.int64(6500), np.int64(28560000))

In [158]:
fact_book.revenue_generated.describe()

count    1.345780e+05
mean     1.537804e+04
std      9.304015e+04
min      6.500000e+03
25%      9.900000e+03
50%      1.350000e+04
75%      1.800000e+04
max      2.856000e+07
Name: revenue_generated, dtype: float64

In [159]:
#we use avg+STD(3) to find normal max 
# remove those max values it is not possible to generate that much revenue in one booking so we usse STD(3) to remove those outliers
avg_gen,std_gen=fact_book.revenue_generated.mean(),fact_book.revenue_generated.std()
avg_gen,std_gen

(np.float64(15378.036937686695), np.float64(93040.1549314641))

In [160]:
#to get max values of an column avrerage + 3*std
max_gen=avg_gen+3*std_gen
max_gen

np.float64(294498.50173207896)

In [161]:
#we use avg- STD(3) to find normal max 
# but revenue is not negative so ve dont use this
min_gen=avg_gen-3*std_gen
min_gen

np.float64(-263742.4278567056)

In [162]:
fact_book[fact_book.revenue_generated>max_gen]

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
2,May012216558RT13,16558,2022-04-28,2022-05-01,2022-05-04,2.0,RT1,logtrip,5.0,Checked Out,9100000,9100
111,May012216559RT32,16559,2022-04-29,2022-05-01,2022-05-02,6.0,RT3,direct online,NaN,Checked Out,28560000,28560
315,May012216562RT22,16562,2022-04-28,2022-05-01,2022-05-04,2.0,RT2,direct offline,3.0,Checked Out,12600000,12600
562,May012217559RT118,17559,2022-04-26,2022-05-01,2022-05-02,2.0,RT1,others,NaN,Cancelled,2000000,4420
129176,Jul282216562RT26,16562,2022-07-21,2022-07-28,2022-07-29,2.0,RT2,direct online,3.0,Checked Out,10000000,12600

In [163]:
#to reomve those otliers in genrated rev
fact_book=fact_book[fact_book.revenue_generated<max_gen]
fact_book.head(6)

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
1,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2.0,RT1,others,NaN,Cancelled,9100,3640
4,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4.0,RT1,direct online,5.0,Checked Out,10920,10920
5,May012216558RT16,16558,2022-05-01,2022-05-01,2022-05-03,2.0,RT1,others,4.0,Checked Out,9100,9100
6,May012216558RT17,16558,2022-04-28,2022-05-01,2022-05-06,2.0,RT1,others,NaN,Cancelled,9100,3640
7,May012216558RT18,16558,2022-04-26,2022-05-01,2022-05-03,2.0,RT1,logtrip,NaN,No Show,9100,9100
8,May012216558RT19,16558,2022-04-30,2022-05-01,2022-05-02,2.0,RT1,tripster,NaN,Checked Out,9100,9100

In [164]:
fact_book.revenue_generated.min(),fact_book.revenue_generated.max()

(np.int64(6500), np.int64(45220))

In [165]:
fact_book.revenue_realized.min(),fact_book.revenue_realized.max()

(np.int64(2600), np.int64(45220))

In [166]:
fact_book.revenue_realized.describe()

count    134573.000000
mean      12695.983585
std        6927.791692
min        2600.000000
25%        7600.000000
50%       11700.000000
75%       15300.000000
max       45220.000000
Name: revenue_realized, dtype: float64

In [167]:
avg_rea,sdt_rea=fact_book.revenue_realized.mean(),fact_book.revenue_realized.std()
print(avg_rea,sdt_rea)
max_rea=avg_rea + 3 * sdt_rea
print(max_rea)
print(12695+3*6927)

12695.983585117372 6927.791692242814
33479.358661845814
33476

In [168]:
fact_book[fact_book.revenue_realized>max_rea]

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
137,May012216559RT41,16559,2022-04-27,2022-05-01,2022-05-07,4.0,RT4,others,NaN,Checked Out,38760,38760
139,May012216559RT43,16559,2022-05-01,2022-05-01,2022-05-02,6.0,RT4,tripster,3.0,Checked Out,45220,45220
143,May012216559RT47,16559,2022-04-28,2022-05-01,2022-05-03,3.0,RT4,others,5.0,Checked Out,35530,35530
149,May012216559RT413,16559,2022-04-24,2022-05-01,2022-05-07,5.0,RT4,logtrip,NaN,Checked Out,41990,41990
222,May012216560RT45,16560,2022-04-30,2022-05-01,2022-05-03,5.0,RT4,others,3.0,Checked Out,34580,34580
...,...,...,...,...,...,...,...,...,...,...,...,...
134328,Jul312219560RT49,19560,2022-07-31,2022-07-31,2022-08-02,6.0,RT4,direct online,5.0,Checked Out,39900,39900
134331,Jul312219560RT412,19560,2022-07-31,2022-07-31,2022-08-01,6.0,RT4,others,2.0,Checked Out,39900,39900
134467,Jul312219562RT45,19562,2022-07-28,2022-07-31,2022-08-01,6.0,RT4,makeyourtrip,4.0,Checked Out,39900,39900
134474,Jul312219562RT412,19562,2022-07-25,2022-07-31,2022-08-06,5.0,RT4,direct offline,5.0,Checked Out,37050,37050
134581,Jul312217564RT42,17564,2022-07-31,2022-07-31,2022-08-01,4.0,RT4,makeyourtrip,4.0,Checked Out,38760,38760

In [169]:
#all max revenue_realized from RT4 room it is Presidential so it is fine also we want to check
dim_rooms

  room_id    room_class
0     RT1      Standard
1     RT2         Elite
2     RT3       Premium
3     RT4  Presidential

In [170]:
fact_book[fact_book.room_category=="RT4"].revenue_realized.describe()

count    16071.000000
mean     23439.308444
std       9048.599076
min       7600.000000
25%      19000.000000
50%      26600.000000
75%      32300.000000
max      45220.000000
Name: revenue_realized, dtype: float64

In [171]:
print(23439+3*9048)

50583

In [172]:
fact_book[(fact_book.room_category!='RT4') & (fact_book.revenue_realized>max_rea) ]
#so RT4 only as high realized rev so its fine

Empty DataFrame
Columns: [booking_id, property_id, booking_date, check_in_date, checkout_date, no_guests, room_category, booking_platform, ratings_given, booking_status, revenue_generated, revenue_realized]
Index: []

In [173]:
fact_book.isnull().sum()
#all column not have null expect ratings_given because all are not give rating so its fine

booking_id               0
property_id              0
booking_date             0
check_in_date            0
checkout_date            0
no_guests                0
room_category            0
booking_platform         0
ratings_given        77897
booking_status           0
revenue_generated        0
revenue_realized         0
dtype: int64

In [174]:
fact_book = fact_book.reset_index(drop=True)
fact_book.head(7)

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2.0,RT1,others,NaN,Cancelled,9100,3640
1,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4.0,RT1,direct online,5.0,Checked Out,10920,10920
2,May012216558RT16,16558,2022-05-01,2022-05-01,2022-05-03,2.0,RT1,others,4.0,Checked Out,9100,9100
3,May012216558RT17,16558,2022-04-28,2022-05-01,2022-05-06,2.0,RT1,others,NaN,Cancelled,9100,3640
4,May012216558RT18,16558,2022-04-26,2022-05-01,2022-05-03,2.0,RT1,logtrip,NaN,No Show,9100,9100
5,May012216558RT19,16558,2022-04-30,2022-05-01,2022-05-02,2.0,RT1,tripster,NaN,Checked Out,9100,9100
6,May012216558RT110,16558,2022-04-28,2022-05-01,2022-05-02,1.0,RT1,others,4.0,Checked Out,9100,9100

**fact_aggregated_bookings==fact_abook**

In [175]:
fact_abook

      property_id check_in_date room_category  successful_bookings  capacity
0           16559    2022-05-01           RT1                   25      30.0
1           19562    2022-05-01           RT1                   28      30.0
2           19563    2022-05-01           RT1                   23      30.0
3           17558    2022-05-01           RT1                   30      19.0
4           16558    2022-05-01           RT1                   18      19.0
...           ...           ...           ...                  ...       ...
9195        16563    2022-07-31           RT4                   13      18.0
9196        16559    2022-07-31           RT4                   13      18.0
9197        17558    2022-07-31           RT4                    3       6.0
9198        19563    2022-07-31           RT4                    3       6.0
9199        17561    2022-07-31           RT4                    3       4.0

[9200 rows x 5 columns]

In [176]:
fact_abook.info()

<class 'pandas.DataFrame'>
RangeIndex: 9200 entries, 0 to 9199
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   property_id          9200 non-null   int64
 1   check_in_date        9200 non-null   datetime64[us]
 2   room_category        9200 non-null   str
 3   successful_bookings  9200 non-null   int64
 4   capacity             9198 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(2), str(1)
memory usage: 359.5 KB

In [177]:
fact_abook.describe()

        property_id        check_in_date  successful_bookings     capacity
count   9200.000000                 9200          9200.000000  9198.000000
mean   18040.640000  2022-06-15 12:00:00            14.655761    25.280496
min    16558.000000  2022-05-01 00:00:00             1.000000     3.000000
25%    17558.000000  2022-05-23 18:00:00             9.000000    18.000000
50%    17564.000000  2022-06-15 12:00:00            14.000000    25.000000
75%    18563.000000  2022-07-08 06:00:00            19.000000    34.000000
max    19563.000000  2022-07-31 00:00:00           123.000000    50.000000
std     1099.818325                  NaN             7.736170    11.442080

In [178]:
fact_abook.isnull().sum()

property_id            0
check_in_date          0
room_category          0
successful_bookings    0
capacity               2
dtype: int64

In [179]:
fact_abook[fact_abook.capacity.isnull()]

    property_id check_in_date room_category  successful_bookings  capacity
8         17561    2022-05-01           RT1                   22       NaN
14        17562    2022-05-01           RT1                   12       NaN

In [180]:
fact_abook[fact_abook.capacity.isna()]

    property_id check_in_date room_category  successful_bookings  capacity
8         17561    2022-05-01           RT1                   22       NaN
14        17562    2022-05-01           RT1                   12       NaN

In [181]:
fact_abook.capacity=fact_abook.capacity.fillna(fact_abook.capacity.median())

In [182]:
fact_abook.isnull().sum()

property_id            0
check_in_date          0
room_category          0
successful_bookings    0
capacity               0
dtype: int64

In [183]:
fact_abook.loc[[8,14]]

    property_id check_in_date room_category  successful_bookings  capacity
8         17561    2022-05-01           RT1                   22      25.0
14        17562    2022-05-01           RT1                   12      25.0

In [184]:
fact_abook[fact_abook.successful_bookings>fact_abook.capacity]

      property_id check_in_date room_category  successful_bookings  capacity
3           17558    2022-05-01           RT1                   30      19.0
12          16563    2022-05-01           RT1                  100      41.0
4136        19558    2022-06-11           RT2                   50      39.0
6209        19560    2022-07-02           RT1                  123      26.0
8522        19559    2022-07-25           RT1                   35      24.0
9194        18563    2022-07-31           RT4                   20      18.0

In [185]:
fact_abook.shape

(9200, 5)

In [186]:
fact_abook=fact_abook[fact_abook.successful_bookings<=fact_abook.capacity]

In [187]:
fact_abook.shape

(9194, 5)

In [188]:
fact_abook[fact_abook.successful_bookings>fact_abook.capacity]

Empty DataFrame
Columns: [property_id, check_in_date, room_category, successful_bookings, capacity]
Index: []

In [189]:
fact_abook.head(15)
#in this we see index 3,12,4136, missing so we use **Reset index after filtering to align with fact_book**

    property_id check_in_date room_category  successful_bookings  capacity
0         16559    2022-05-01           RT1                   25      30.0
1         19562    2022-05-01           RT1                   28      30.0
2         19563    2022-05-01           RT1                   23      30.0
4         16558    2022-05-01           RT1                   18      19.0
5         17560    2022-05-01           RT1                   28      40.0
6         19558    2022-05-01           RT1                   25      40.0
7         19560    2022-05-01           RT1                   23      26.0
8         17561    2022-05-01           RT1                   22      25.0
9         16560    2022-05-01           RT1                   24      34.0
10        16561    2022-05-01           RT1                   16      18.0
11        16562    2022-05-01           RT1                   20      31.0
13        17559    2022-05-01           RT1                   26      32.0
14        17562    2022-05-01           RT1                   12      25.0
15        17563    2022-05-01           RT1                   21      25.0
16        18558    2022-05-01           RT1                   11      15.0

In [190]:
# Reset index after filtering to align with fact_book
fact_abook = fact_abook.reset_index(drop=True)

In [191]:
fact_abook["occ_rate"]=fact_abook.apply(lambda x: x['successful_bookings']/x['capacity'],axis=1)
fact_abook.head(5)

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_rate
0,16559,2022-05-01,RT1,25,30.0,0.833333
1,19562,2022-05-01,RT1,28,30.0,0.933333
2,19563,2022-05-01,RT1,23,30.0,0.766667
3,16558,2022-05-01,RT1,18,19.0,0.947368
4,17560,2022-05-01,RT1,28,40.0,0.700000

In [192]:
fact_abook["occ_rate"]=fact_abook["occ_rate"].apply(lambda x: round(x*100,2))
fact_abook.head(5)

,property_id,check_in_date,room_category,successful_bookings,capacity,occ_rate
0,16559,2022-05-01,RT1,25,30.0,83.33
1,19562,2022-05-01,RT1,28,30.0,93.33
2,19563,2022-05-01,RT1,23,30.0,76.67
3,16558,2022-05-01,RT1,18,19.0,94.74
4,17560,2022-05-01,RT1,28,40.0,70.00

In [193]:
fact_abook.info()

<class 'pandas.DataFrame'>
RangeIndex: 9194 entries, 0 to 9193
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   property_id          9194 non-null   int64
 1   check_in_date        9194 non-null   datetime64[us]
 2   room_category        9194 non-null   str
 3   successful_bookings  9194 non-null   int64
 4   capacity             9194 non-null   float64
 5   occ_rate             9194 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(1)
memory usage: 431.1 KB

In [194]:
fact_abook.describe()

,property_id,check_in_date,successful_bookings,capacity,occ_rate
count,9194.000000,9194,9194.000000,9194.000000,9194.000000
mean,18040.300957,2022-06-15 11:59:03.615401,14.626387,25.278769,58.301489
min,16558.000000,2022-05-01 00:00:00,1.000000,3.000000,21.050000
25%,17558.000000,2022-05-24 00:00:00,9.000000,18.000000,47.370000
50%,17564.000000,2022-06-15 12:00:00,14.000000,25.000000,56.250000
75%,18563.000000,2022-07-08 00:00:00,19.000000,34.000000,66.670000
max,19563.000000,2022-07-31 00:00:00,43.000000,50.000000,100.000000
std,1099.702158,NaN,7.589974,11.442051,15.267240

In [195]:
fact_book.head(6)

,booking_id,property_id,booking_date,check_in_date,checkout_date,no_guests,room_category,booking_platform,ratings_given,booking_status,revenue_generated,revenue_realized
0,May012216558RT12,16558,2022-04-30,2022-05-01,2022-05-02,2.0,RT1,others,NaN,Cancelled,9100,3640
1,May012216558RT15,16558,2022-04-27,2022-05-01,2022-05-02,4.0,RT1,direct online,5.0,Checked Out,10920,10920
2,May012216558RT16,16558,2022-05-01,2022-05-01,2022-05-03,2.0,RT1,others,4.0,Checked Out,9100,9100
3,May012216558RT17,16558,2022-04-28,2022-05-01,2022-05-06,2.0,RT1,others,NaN,Cancelled,9100,3640
4,May012216558RT18,16558,2022-04-26,2022-05-01,2022-05-03,2.0,RT1,logtrip,NaN,No Show,9100,9100
5,May012216558RT19,16558,2022-04-30,2022-05-01,2022-05-02,2.0,RT1,tripster,NaN,Checked Out,9100,9100

In [196]:
# Export cleaned data to CSV files
output_dir = r'C:\projects_monish\Hotel Analytics\Hotel-analytics\data\clean'

fact_book.to_csv(f"{output_dir}/fact_bookings_clean.csv", index=False)
fact_abook.to_csv(f"{output_dir}/fact_aggregated_bookings_clean.csv", index=False)
dim_hotels.to_csv(f"{output_dir}/dim_hotels_clean.csv", index=False)
dim_rooms.to_csv(f"{output_dir}/dim_rooms_clean.csv", index=False)
dim_date.to_csv(f"{output_dir}/dim_date_clean.csv", index=False)

print("All cleaned files exported successfully!")

All cleaned files exported successfully!